<?php

use Drupal\node\Entity\NodeType;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

  function node_compare_theme($existing, $type, $theme, $path) {
    $path = drupal_get_path('module', 'node_compare') . '/theme';
    
    return array(
      'node_compare_display' => [
        'variables' => array(
            'comparison_table' => NULL,
          ),
        'template' => 'node-compare-template',
      ],
      'node_compare_block_content' => [
        'variables' => [
          'type' => NULL,
          'nids' => [],
        ],
        'path' => $path,
      ],
      'node_compare_toggle_link' => [
        'variables' => [
          'nid' => NULL,
          'block' => FALSE,
        ],
        'path' => $path
      ],
      
    );
    
  }
  
  /**
 * Preprocess for the comparison page.
 */
  
  function template_preprocess_node_compare_comparison_page(&$vars) {
    $vars['only_diff_checkbox'] = array(
      '#type' => 'checkbox',
      '#title' => variable_get('node_compare_only_diff', 'Show differences'),
      '#attributes' => array(
        'id' => array('compare-only-diff'),
      ),
      '#prefix' => '<div id="compare-view-mode-box" style="display: none">',
      '#suffix' => '</div>',
    );
  
    $vars['comparison_table']['#prefix'] = '<div id="compare-content-wrapper">';
    $vars['comparison_table']['#suffix'] = '</div>';
    $vars['comparison_table']['#attributes'] = array(
      'id' => 'comparison-table',
    );
    $vars['comparison_table']['#attached'] = array(
      'js' => array(
        drupal_get_path('module', 'node_compare') . '/theme/compare-table.js',
      ),
    );
  }
  

  
  /**
 * Implements hook_entity_extra_field_info().
 */
    function node_compare_entity_extra_field_info() {
      $extra = array();
      $type = \Drupal::entityTypeManager()->getStorage('node_type')->loadMultiple();
      foreach ($type as $bundle) {  
        kint(\Drupal::state()->get('node_compare.node_compare_' . $bundle->get('type'), array()));
        if (\Drupal::state()->get('node_compare.node_compare_' . $bundle->get('type'), array())){
          $extra['node'][$bundle->get('type')]['display']['node_compare_link'] = array(
            'label' => t('My own field'),
            'description' => t('This is my own pseudo-field'),
            'weight' => 100,
            'visible' => TRUE,
          );
        }
      } 
     
      return $extra;
    }
  
      /**
      * Implements hook_ENTITY_TYPE_view().
      */
    function node_compare_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode, $langcode) {
      if ($display->getComponent('node_compare_link')) {
          $build['node_compare_link'] = [
            'id' => 'node_compare_toggle_link',
            '#type' => 'checkbox',
            '#nid' => $entity->id,
            #'#weight' => $entity['node_compare_link']['weight'],
        ];
      }
      
    } 